name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies for Frontend
        working-directory: ./frontend
        run: npm install

      - name: Run tests for Frontend
        working-directory: ./frontend
        run: npm test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Backend (Nest.js)
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v1

      - name: Install dependencies for Backend
        working-directory: ./backend
        run: npm ci

      - name: Run tests for Backend
        working-directory: ./backend
        run: npm test

      - name: Build Backend
        working-directory: ./backend
        run: npm ci && npm run build
